### ISSUE TITLE
Why not using --turbo?

### ISSUE THREAD

**Issue by patelvivekdev** [aurorascharff/next15-remix-contacts-rebuild-v2#1]

**Comment by aurorascharff** [comment]
Good point, I'll add it!

**Comment by patelvivekdev** [comment]
I have used this repo for reproduction using Drizzle ORM.

I have also enable the PPR.

You can check it here.

https://next-contacts.patelvivekdev.vercel.app

**Comment by aurorascharff** [comment]
> I have used this repo for reproduction using Drizzle ORM.
> 
> I have also enable the PPR.
> 
> You can check it here.
> 
> https://next-contacts.patelvivekdev.vercel.app

Awesome! Thanks for letting me know :D
